[test]
coverageReporter = [
  "text",
  "lcov"
]
coveragePathIgnorePatterns = [
  # do not report untouched files to avoid overlap with other coverage reports
  # merged coverage reports can be misleading
  "../**",
  "**/*.test.*",
  "**/tests/**",
]
